### PR TITLE
User/jni2/date time format

### PR DESCRIPTION
**Pull request by JNI2**
Changed date and time format for attribute generationDateAndTime to "yyyy-MM-ddTHH:mm:ssZ".

### CODE REVIEW

**Comment by christoff-buerger** [comment]
@JNI2: I assume this change will generate proper dates when adding or updating containers.
Does it also report broken dates? Hence, when checking containers does abort with an error when manifest `generationDateAndTime` attributes are in an invalid format?

**Review by christoff-buerger — APPROVED** [review]
Looks good.

**Comment by JNI2** [comment]
Thanks Christoff. And No, the Container Manager does not check the date/time format when reading/modifying a container.

**Comment by christoff-buerger** [comment]
> Thanks Christoff. And No, the Container Manager does not check the date/time format when reading/modifying a container.

That is Ok. We should probably force the correct format via a pattern in the XSD Schemas anyway.

I guess we need a new distribution of the _eFMI Container Manager_ so @gkurzbach can use the corrected version. But I would try to avoid this until we are sure there is nothing more coming up.
@gkurzbach can you use the sources for now? You can use the `build-release.bat` to compile everything on a Windows machine (assuming you have Microsoft Visual Studio).

**Pull request merged**
